### ISSUE TITLE
util-linux in older version will caused error in `gpud` scan or run

### ISSUE THREAD

**Issue by sunhailin-Leo** [leptonai/gpud#272]
## Abstracts:
* In older systems like CentOS 7.9 with an older `util-linux` version, using `gpud` will cause some errors. 
* Below is the error when `lsblk` version is too old that `gpud` cannot parse disk info.
* Also, `dmesg` meet the same problem. Straight to here --> https://github.com/leptonai/gpud/issues/272#issuecomment-2564663624

TL;DR; 😄 

## Quesion:
* In CentOS 7.9 `lsblk` version default is `lsblk，来自 util-linux 2.23.2`, but RockyLinux 9 is `lsblk from util-linux 2.37.4`

*`lsblk` 2.23.2: 
```shell

用法：
 lsblk [选项] [<设备> ...]

选项：
 -a, --all            打印所有设备
 -b, --bytes          以字节为单位而非易读的格式来打印 SIZE
 -d, --nodeps         不打印从属设备(slave)或占位设备(holder)
 -D, --discard        打印时丢弃能力
 -e, --exclude <列表> 根据主设备号排除设备(默认：内存盘)
 -I, --include <列表> 只显示有指定主设备号的设备
 -f, --fs             输出文件系统信息
 -h, --help           使用信息(此信息)
 -i, --ascii          只使用 ascii 字符
 -m, --perms          输出权限信息
 -l, --list           使用列表格式的输出
 -n, --noheadings     不打印标题
 -o, --output <列表>  输出列
 -p, --paths          打印完整设备路径
 -P, --pairs          使用 key=“value” 输出格式
 -r, --raw            使用原生输出格式
 -s, --inverse        反向依赖
 -t, --topology       输出拓扑信息
 -S, --scsi           输出有关 SCSI 设备的信息

 -h, --help     显示此帮助并退出
 -V, --version  输出版本信息并退出

可用列(用于 --output)：
        NAME  设备名
       KNAME  internal kernel device name
     MAJ:MIN  主:次 设备号
      FSTYPE  文件系统类型
  MOUNTPOINT  where the device is mounted
       LABEL  filesystem LABEL
        UUID  filesystem UUID
   PARTLABEL  分区 LABEL
    PARTUUID  分区 UUID
          RA  read-ahead of the device
          RO  只读设备
          RM  removable device
       MODEL  device identifier
      SERIAL  disk serial number
        SIZE  size of the device
       STATE  设备的状态
       OWNER  user name
       GROUP  group name
        MODE  device node permissions
   ALIGNMENT  alignment offset
      MIN-IO  minimum I/O size
      OPT-IO  optimal I/O size
     PHY-SEC  物理扇区大小
     LOG-SEC  逻辑扇区大小
        ROTA  rotational device
       SCHED  I/O scheduler name
     RQ-SIZE  request queue size
        TYPE  device type
    DISC-ALN  discard alignment offset
   DISC-GRAN  discard granularity
    DISC-MAX  discard max bytes
   DISC-ZERO  忽略零数据
       WSAME  write same max bytes
         WWN  unique storage identifier
        RAND  adds randomness
      PKNAME  internal parent kernel device name
        HCTL  Host:Channel:Target:Lun for SCSI
        TRAN  device transport type
         REV  device revision
      VENDOR  device vendor

更多信息请参阅 lsblk(8)。
```

* Higher than lsblk 2.23.2:
```shell

Usage:
 lsblk [options] [<device> ...]

List information about block devices.

Options:
 -D, --discard        print discard capabilities
 -E, --dedup <column> de-duplicate output by <column>
 -I, --include <list> show only devices with specified major numbers
 -J, --json           use JSON output format
 -O, --output-all     output all columns
 -P, --pairs          use key="value" output format
 -S, --scsi           output info about SCSI devices
 -T, --tree[=<column>] use tree format output
 -a, --all            print all devices
 -b, --bytes          print SIZE in bytes rather than in human readable format
 -d, --nodeps         don't print slaves or holders
 -e, --exclude <list> exclude devices by major number (default: RAM disks)
 -f, --fs             output info about filesystems
 -i, --ascii          use ascii characters only
 -l, --list           use list format output
 -M, --merge          group parents of sub-trees (usable for RAIDs, Multi-path)
 -m, --perms          output info about permissions
 -n, --noheadings     don't print headings
 -o, --output <list>  output columns
 -p, --paths          print complete device path
 -r, --raw            use raw output format
 -s, --inverse        inverse dependencies
 -t, --topology       output info about topology
 -w, --width <num>    specifies output width as number of characters
 -x, --sort <column>  sort output by <column>
 -z, --zoned          print zone model
     --sysroot <dir>  use specified directory as system root

 -h, --help           display this help
 -V, --version        display version

Available output columns:
         NAME  device name
        KNAME  internal kernel device name
         PATH  path to the device node
      MAJ:MIN  major:minor device number
      FSAVAIL  filesystem size available
       FSSIZE  filesystem size
       FSTYPE  filesystem type
       FSUSED  filesystem size used
       FSUSE%  filesystem use percentage
      FSROOTS  mounted filesystem roots
        FSVER  filesystem version
   MOUNTPOINT  where the device is mounted
  MOUNTPOINTS  all locations where device is mounted
        LABEL  filesystem LABEL
         UUID  filesystem UUID
       PTUUID  partition table identifier (usually UUID)
       PTTYPE  partition table type
     PARTTYPE  partition type code or UUID
 PARTTYPENAME  partition type name
    PARTLABEL  partition LABEL
     PARTUUID  partition UUID
    PARTFLAGS  partition flags
           RA  read-ahead of the device
           RO  read-only device
           RM  removable device
      HOTPLUG  removable or hotplug device (usb, pcmcia, ...)
        MODEL  device identifier
       SERIAL  disk serial number
         SIZE  size of the device
        STATE  state of the device
        OWNER  user name
        GROUP  group name
         MODE  device node permissions
    ALIGNMENT  alignment offset
       MIN-IO  minimum I/O size
       OPT-IO  optimal I/O size
      PHY-SEC  physical sector size
      LOG-SEC  logical sector size
         ROTA  rotational device
        SCHED  I/O scheduler name
      RQ-SIZE  request queue size
         TYPE  device type
     DISC-ALN  discard alignment offset
    DISC-GRAN  discard granularity
     DISC-MAX  discard max bytes
    DISC-ZERO  discard zeroes data
        WSAME  write same max bytes
          WWN  unique storage identifier
         RAND  adds randomness
       PKNAME  internal parent kernel device name
         HCTL  Host:Channel:Target:Lun for SCSI
         TRAN  device transport type
   SUBSYSTEMS  de-duplicated chain of subsystems
          REV  device revision
       VENDOR  device vendor
        ZONED  zone model
          DAX  dax-capable device

For more details see lsblk(8).
``` 

* Higher than `lsblk` verison 2.26 with (start at 2.27) `--json`: https://github.com/util-linux/util-linux/blob/stable/v2.27/misc-utils/lsblk.c#L138

## Error

* `lsblk` version different will caused `gpud run` error like below:
```shell
{"level":"info","ts":"2024-12-27T12:31:59+08:00","caller":"command/run.go:111","msg":"starting gpud fa9c0e5"}
{"level":"info","ts":"2024-12-27T12:31:59+08:00","caller":"informer/file_informer.go:137","msg":"Watching directory: /var/lib/gpud/"}
{"level":"info","ts":"2024-12-27T12:31:59+08:00","caller":"server/server.go:189","msg":"api version","version":"v1"}
{"level":"warn","ts":"2024-12-27T12:31:59+08:00","caller":"process/process.go:269","msg":"command exited with non-zero status","error":"exit status 1","cmd":"/bin/bash /tmp/tmpbash2769924549.bash","exitCode":1}
{"level":"warn","ts":"2024-12-27T12:31:59+08:00","caller":"process/process.go:276","msg":"process exited with error","error":"exit status 1"}
{"level":"error","ts":"2024-12-27T12:31:59+08:00","caller":"log/log.go:60","msg":"failed to get block devices","error":"failed to read lsblk output: exit status 1\n\noutput:\n/bin/lsblk：无法识别的选项“--json”\n\n用法：\n lsblk [选项] [<设备> ...]\n\n选项：\n -a, --all            打印所有设备\n -b, --bytes          以字节为单位而非易读的格式来打印 SIZE\n -d, --nodeps         不打印从属设备(slave)或占位设备(holder)\n -D, --discard        打印时丢弃能力\n -e, --exclude <列表> 根据主设备号排除设备(默认：内存盘)\n -I, --include <列表> 只显示有指定主设备号的设备\n -f, --fs             输出文件系统信息\n -h, --help           使用信息(此信息)\n -i, --ascii          只使用 ascii 字符\n -m, --perms          输出权限信息\n -l, --list           使用列表格式的输出\n -n, --noheadings     不打印标题\n -o, --output <列表>  输出列\n -p, --paths          打印完整设备路径\n -P, --pairs          使用 key=“value” 输出格式\n -r, --raw            使用原生输出格式\n -s, --inverse        反向依赖\n -t, --topology       输出拓扑信息\n -S, --scsi           输出有关 SCSI 设备的信息\n\n -h, --help     显示此帮助并退出\n -V, --version  输出版本信息并退出\n\n可用列(用于 --output)：\n        NAME  设备名\n       KNAME  internal kernel device name\n     MAJ:MIN  主:次 设备号\n      FSTYPE  文件系统类型\n  MOUNTPOINT  where the device is mounted\n       LABEL  filesystem LABEL\n        UUID  filesystem UUID\n   PARTLABEL  分区 LABEL\n    PARTUUID  分区 UUID\n          RA  read-ahead of the device\n          RO  只读设备\n          RM  removable device\n       MODEL  device identifier\n      SERIAL  disk serial number\n        SIZE  size of the device\n       STATE  设备的状态\n       OWNER  user name\n       GROUP  group name\n        MODE  device node permissions\n   ALIGNMENT  alignment offset\n      MIN-IO  minimum I/O size\n      OPT-IO  optimal I/O size\n     PHY-SEC  物理扇区大小\n     LOG-SEC  逻辑扇区大小\n        ROTA  rotational device\n       SCHED  I/O scheduler name\n     RQ-SIZE  request queue size\n        TYPE  device type\n    DISC-ALN  discard alignment offset\n   DISC-GRAN  discard granularity\n    DISC-MAX  discard max bytes\n   DISC-ZERO  忽略零数据\n       WSAME  write same max bytes\n         WWN  unique storage identifier\n        RAND  adds randomness\n      PKNAME  internal parent kernel device name\n        HCTL  Host:Channel:Target:Lun for SCSI\n        TRAN  device transport type\n         REV  device revision\n      VENDOR  device vendor\n\n更多信息请参阅 lsblk(8)。","stacktrace":"github.com/leptonai/gpud/log.(*LeptonLogger).Errorw\n\t/root/gpud/log/log.go:60\ngithub.com/leptonai/gpud/components/disk.setDefaultPoller.func1.CreateGet.2\n\t/root/gpud/components/disk/component_output.go:209\ngithub.com/leptonai/gpud/components/query.pollLoops\n\t/root/gpud/components/query/poller.go:154"}
{"level":"warn","ts":"2024-12-27T12:31:59+08:00","caller":"process/process.go:269","msg":"command exited with non-zero status","error":"exit status 1","cmd":"/bin/bash /tmp/tmpbash3772265674.bash","exitCode":1}
{"level":"warn","ts":"2024-12-27T12:31:59+08:00","caller":"process/process.go:276","msg":"process exited with error","error":"exit status 1"}
panic: command exited unexpectedly: exit status 1

goroutine 1 [running]:
github.com/leptonai/gpud/components/dmesg.createDefaultLogPoller.func1()
	/root/gpud/components/dmesg/poller.go:28 +0x125
sync.(*Once).doSlow(0xc000522708?, 0xc0003719a0?)
	/root/.gvm/gos/go1.23.3/src/sync/once.go:76 +0xb4
sync.(*Once).Do(...)
	/root/.gvm/gos/go1.23.3/src/sync/once.go:67
github.com/leptonai/gpud/components/dmesg.createDefaultLogPoller({0x1c8e9b0?, 0xc00037f900?}, {{{{0xdf8475800}, {0x61c9f36800}, 0x7d0, 0xc0003aeb70}, 0x7d0, {0x0, 0x0}, {0xc001096bd0, ...}, ...}}, ...)
	/root/gpud/components/dmesg/poller.go:20 +0x6e
github.com/leptonai/gpud/components/dmesg.New({0x1c8e9b0, 0xc00037f900}, {{{{0xdf8475800}, {0x61c9f36800}, 0x3c, 0xc0003aeb70}, 0x7d0, {0x0, 0x0}, {0xc001096bd0, ...}, ...}}, ...)
	/root/gpud/components/dmesg/component.go:25 +0x252
github.com/leptonai/gpud/internal/server.New({0x1c8e9b0, 0xc00037f900}, 0xc0003ca2a0, {0x19fb105, 0x20}, {0x0, 0x0}, 0xc00019e010, {0xc0000557a0, 0x4, ...})
	/root/gpud/internal/server/server.go:518 +0x9f74
github.com/leptonai/gpud/cmd/gpud/command.cmdRun(0xc000042dc0)
	/root/gpud/cmd/gpud/command/run.go:123 +0x8be
github.com/urfave/cli.HandleAction({0x1714640?, 0x1acb350?}, 0x3?)
	/root/.gvm/pkgsets/go1.23.3/global/pkg/mod/github.com/urfave/cli@v1.22.15/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x19b9db5, 0x3}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1a48de0, 0x4a}, {0x0, ...}, ...}, ...)
	/root/.gvm/pkgsets/go1.23.3/global/pkg/mod/github.com/urfave/cli@v1.22.15/command.go:175 +0x67c
github.com/urfave/cli.(*App).Run(0xc000704700, {0xc000040060, 0x2, 0x2})
	/root/.gvm/pkgsets/go1.23.3/global/pkg/mod/github.com/urfave/cli@v1.22.15/app.go:277 +0xb3b
main.main()
	/root/gpud/cmd/gpud/main.go:12 +0x2d
```

## Solution: 
* 1. I think before exec this line https://github.com/leptonai/gpud/blob/main/pkg/disk/lsblk.go#L55 may check `lsblk` version. If `lsblk` have `--json` args then use current parse method. If not, try another way to parse it.
* 2. update system `util-linux` version higher than 2.26 (not recommended, may caused some kernel problem)

**Comment by gyuho** [comment]
Thanks for the report, looking into the fix

**Comment by sunhailin-Leo** [comment]
> Thanks for the report, looking into the fix

* I tried to fix the problem. The code is here: https://github.com/sunhailin-Leo/gpud/commit/261089dfbf1d765efc45a1319d0dd7a8483d2004
* But, I found another error in `dmesg`, also caused by `util-linux` version is too old.

**Comment by sunhailin-Leo** [comment]
@gyuho 
* For the second question, I plan to use `journalctl` to solve it because `journalctl` has better compatibility than `dmesg`.Or I think using `journalctl` to replace `dmesg`, because `dmesg` has relatively large compatibility issues caused by `util-linux` version differences.

---
 
* In addition, have you encountered a situation where the times returned by `dmesg` and `journalctl` are inconsistent in your usage scenarios?  
![image](https://github.com/user-attachments/assets/be3d3a52-f871-46c6-8a62-7ec2f104a594)

* I also found that the formatted time obtained by `journalctl` is more accurate than that of `dmesg` when I used different machines for experiments. (The problem may lie in their inconsistent ways of obtaining system time, etc.)

**Comment by sunhailin-Leo** [comment]
All problems are solved.
* https://github.com/leptonai/gpud/commit/bfb70b4b0d39839c891b5d72aabce0ce8b9a58a8
* https://github.com/leptonai/gpud/commit/8a85e09cb796f4033627bbfd542c80c57690a3e5
